service: phone-connector

frameworkVersion: ">=1.1.0"

projectDir: ../../

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs14.x
  # TODO: handle deployment bucket in local
  # deploymentBucket: ${ssm:s3-serverless-deployment}
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${self:provider.stage}

custom:
  localstack:
    stages:
      - local

functions:
  send-sms:
    handler: src/handler.sendSMS
  test:
    handler: src/handler.test1

resources:
  Resources:
    phonesDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: phones
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: number
            AttributeType: S
        KeySchema:
          - AttributeName: number
            KeyType: HASH