version: "3.9"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:0.12.16
    restart: "on-failure"
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,s3,dynamodb,sns,sqs,ssm,apigateway,cloudformation,cloudwatch,sts,iam,events
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - INIT_SCRIPTS_PATH=/init
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - AWS_ACCESS_KEY_ID=foo 
      - AWS_SECRET_ACCESS_KEY=bar
    volumes:
      - "${PWD}/.localstack:/tmp/localstack"
      - "${PWD}/bin/bootstrap.sh:/init/bootstrap.sh"
      - /var/run/docker.sock:/var/run/docker.sock      
