version: "3.9"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:0.12.16
    restart: "on-failure"
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,s3,dynamodb,sns,sqs,ssm,apigateway,cloudformation,cloudwatch,sts,iam,events
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - INIT_SCRIPTS_PATH=/init
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=/tmp/localstack
      - AWS_ACCESS_KEY_ID=foo 
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect-brk=0.0.0.0:9230 -p 9230:9230
    volumes:
      - "${PWD}/.localstack:/tmp/localstack"
      - "${PWD}/bin/bootstrap.sh:/init/bootstrap.sh"
      - /var/run/docker.sock:/var/run/docker.sock      
