service: lsdemo-consumer

frameworkVersion: ">=2.4.0"

projectDir: ../../

plugins:
  - serverless-localstack
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  deploymentBucket:
    name: ${ssm:s3-serverless-deployment,"local-marley-sls-deployments"}
  stage: ${opt:stage, 'local'}
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${self:provider.stage}

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true ## Node modules configuration for packaging - needed by hot reloading
    keepOutputDirectory: true ## Output data directory (.webpack) and content must be retained - needed by hot reloading
  localstack:
    stages:
      - local
    lambda:
      mountCode: true

functions:
  direct-invoke:
    handler: src/handler.direct
  queue-invoke:
    handler: src/handler.queue
    events:
      - sqs: ${ssm:lsdemo-my-sqs-queue-arn}

resources:
  Resources:
    myDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my-dynamo-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
